# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lw5_WEDJ8gI8Rnj8zXgy7FdZmFjLiC2
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

temp_arry = ([21, 22, 24, 28, 31, 32, 34])
dias_arry = (['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'])


df = pd.DataFrame({'Dias': dias_arry, 'Temperatura': temp_arry})

print(f'{df}\n')

media = np.mean(temp_arry)
print(f'Média da temperatura: {media:.2f}°C \n')

plt.plot(temp_arry, dias_arry, label = 'Variação da Temperatura')
plt.xlabel('Temperatura °C')
plt.ylabel('Dias da Semana')
plt.grid(True)
plt.legend()
plt.show()